In [10]:
import numpy as np
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

In [31]:
df = pd.DataFrame()
df['V1'] = [1,2,3]
df['V2'] = [1,4,6]
df['v3'] = [1,6,7]
df['V4'] =[1,5,7]
df['V5'] = [9,5,6]

In [32]:
X = df

In [33]:
#PCA valeurs propres et vecteurs propres 
mean_vec = np.mean(X, axis=0)
cov_mat = (X- mean_vec).T.dot((X - mean_vec)) / (X.shape[0])
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

eig_vals = np.real(eig_vals)
eig_vecs = np.real(eig_vecs)
print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.17444798  0.95098155 -0.25534682  0.02513484  0.9440255 ]
 [ 0.45167755 -0.19019631 -0.39976588 -0.10091471 -0.0957915 ]
 [ 0.58557433 -0.05684028  0.18836422  0.76726692 -0.09672036]
 [ 0.55445913 -0.17926549 -0.28883812 -0.4934179  -0.23299482]
 [-0.33945996 -0.15521768 -0.80998562  0.39626344 -0.18973251]]

Eigenvalues 
[ 1.99980618e+01 -8.37076358e-16  8.90827070e-01  9.23256140e-16
 -8.21186889e-16]


In [34]:
#PCA valeurs propres sorted et vecteurs propres sorted
eig_vals_indexed = []
for i in range(len(eig_vals)):
    eig_vals_indexed.append((i,abs(eig_vals[i])))

In [35]:
def getValue(l):
    return l[1]

eig_vals_sorted = sorted(eig_vals_indexed, key=getValue,reverse= True)

In [36]:
eig_vals_sorted

[(0, 19.998061818940442),
 (2, 0.890827069948457),
 (3, 9.232561402352062e-16),
 (1, 8.370763578550955e-16),
 (4, 8.211868892971262e-16)]

In [37]:
index =[]
for i in eig_vals_sorted:
    index.append(i[0])

index

[0, 2, 3, 1, 4]

In [39]:
eig_vecs

array([[ 0.17444798,  0.95098155, -0.25534682,  0.02513484,  0.9440255 ],
       [ 0.45167755, -0.19019631, -0.39976588, -0.10091471, -0.0957915 ],
       [ 0.58557433, -0.05684028,  0.18836422,  0.76726692, -0.09672036],
       [ 0.55445913, -0.17926549, -0.28883812, -0.4934179 , -0.23299482],
       [-0.33945996, -0.15521768, -0.80998562,  0.39626344, -0.18973251]])

In [38]:
eig_vecs_sorted = eig_vecs[index]

In [40]:
eig_vecs_sorted

array([[ 0.17444798,  0.95098155, -0.25534682,  0.02513484,  0.9440255 ],
       [ 0.58557433, -0.05684028,  0.18836422,  0.76726692, -0.09672036],
       [ 0.55445913, -0.17926549, -0.28883812, -0.4934179 , -0.23299482],
       [ 0.45167755, -0.19019631, -0.39976588, -0.10091471, -0.0957915 ],
       [-0.33945996, -0.15521768, -0.80998562,  0.39626344, -0.18973251]])