In [293]:
import numpy as np
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd
import matplotlib.pyplot as plt
import plotly.plotly as py
import plotly.graph_objs as go
from IPython.display import Image
%matplotlib inline

In [294]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original', data_home='datasets/')

# Convert sklearn 'datasets bunch' object to Pandas DataFrames
y = pd.Series(mnist.target).astype('int').astype('category')
X = pd.DataFrame(mnist.data)

In [295]:
new_column_name = []
for num in range(X.shape[1]):
    tem = 'pixel' + str(num)
    new_column_name.append(tem)
X.columns = new_column_name

In [296]:
X.shape

(70000, 784)

In [297]:
X['label'] = y

In [298]:
X = X.sample(70000)

In [299]:
y = X["label"]  # dependent variable
X = X.drop(["label"], axis = 1) #independent variable

In [300]:
X.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
11640       0       0       0       0       0       0       0       0       0   
18279       0       0       0       0       0       0       0       0       0   
23087       0       0       0       0       0       0       0       0       0   
47286       0       0       0       0       0       0       0       0       0   
19353       0       0       0       0       0       0       0       0       0   

       pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
11640       0    ...            0         0         0         0         0   
18279       0    ...            0         0         0         0         0   
23087       0    ...            0         0         0         0         0   
47286       0    ...            0         0         0         0         0   
19353       0    ...            0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
11640         0         0         0         0         0  
18279         0         0         0         0         0  
23087         0         0         0         0         0  
47286         0         0         0         0         0  
19353         0         0         0         0         0  

[5 rows x 784 columns]

In [301]:
#PCA valeurs propres et vecteurs propres 
mean_vec = np.mean(X, axis=0)
cov_mat = (X- mean_vec).T.dot((X - mean_vec)) / (X.shape[0])
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]

Eigenvalues 
[ 3.34289286e+05+0.00000000e+00j  2.45429921e+05+0.00000000e+00j
  2.10927341e+05+0.00000000e+00j  1.85334709e+05+0.00000000e+00j
  1.67689177e+05+0.00000000e+00j  1.47668187e+05+0.00000000e+00j
  1.12443533e+05+0.00000000e+00j  9.91139674e+04+0.00000000e+00j
  9.46111872e+04+0.00000000e+00j  8.03348093e+04+0.00000000e+00j
  7.22588790e+04+0.00000000e+00j  6.98875556e+04+0.00000000e+00j
  5.85518694e+04+0.00000000e+00j  5.81044457e+04+0.00000000e+00j
  5.43096063e+04+0.00000000e+00j  5.09812503e+04+0.00000000e+00j
  4.52536592e+04+0.00000000e+00j  4.38698621e+04+0.00000000e+00j
  4.07231430e+04+0.00000000e+00j  3.95454343e+04+0.00000000e+00j
  3.65648922e+04+0.000

In [302]:
eig_vals = np.real(eig_vals)
eig_vecs = np.real(eig_vecs)
print('Eigenvectors \n', eig_vecs)
print('\nEigenvalues \n', eig_vals)

Eigenvectors 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

Eigenvalues 
 [ 3.34289286e+05  2.45429921e+05  2.10927341e+05  1.85334709e+05
  1.67689177e+05  1.47668187e+05  1.12443533e+05  9.91139674e+04
  9.46111872e+04  8.03348093e+04  7.22588790e+04  6.98875556e+04
  5.85518694e+04  5.81044457e+04  5.43096063e+04  5.09812503e+04
  4.52536592e+04  4.38698621e+04  4.07231430e+04  3.95454343e+04
  3.65648922e+04  3.46356878e+04  3.28986421e+04  3.12002508e+04
  3.02965122e+04  2.87712502e+04  2.77770236e+04  2.69499231e+04
  2.53908053e+04  2.36673094e+04  2.21394661e+04  2.25055712e+04
  2.06079485e+04  2.00863333e+04  1.94395023e+04  1.86409047e+04
  1.73116665e+04  1.67066997e+04  1.64280388e+04  1.60383427e+04
  1.55847279e+04  1.52605741e+04  1.43447224e+04  1.35883208e+04
  1.31610777e+04  1.28893227e+04  1.23968292e+04  1.19714546e+04
  1.16184074e+04  1.09654969e+04  

In [303]:
sum(eig_vecs_sorted[0])

1.0

In [304]:
#PCA valeurs propres sorted et vecteurs propres sorted
eig_vals_indexed = []
for i in range(len(eig_vals)):
    eig_vals_indexed.append((i,abs(eig_vals[i])))

In [305]:
def getValue(l):
    return l[1]

eig_vals_sorted = sorted(eig_vals_indexed, key=getValue,reverse= True)

In [306]:
eig_vals_sorted

[(0, 334289.2857891289),
 (1, 245429.92095245805),
 (2, 210927.3412949326),
 (3, 185334.70864258448),
 (4, 167689.17681018103),
 (5, 147668.18704742036),
 (6, 112443.53257153876),
 (7, 99113.96735172268),
 (8, 94611.18715419022),
 (9, 80334.80928115599),
 (10, 72258.87902671158),
 (11, 69887.55560597668),
 (12, 58551.86939644266),
 (13, 58104.445681429905),
 (14, 54309.60627583975),
 (15, 50981.250275524),
 (16, 45253.659185955315),
 (17, 43869.862084780885),
 (18, 40723.14299596048),
 (19, 39545.43426303235),
 (20, 36564.89221385319),
 (21, 34635.68778016269),
 (22, 32898.64211120598),
 (23, 31200.2507538771),
 (24, 30296.512182196962),
 (25, 28771.25021108979),
 (26, 27777.02361190815),
 (27, 26949.923131589258),
 (28, 25390.805334249137),
 (29, 23667.309365538713),
 (31, 22505.571248460976),
 (30, 22139.46605065026),
 (32, 20607.948540843445),
 (33, 20086.333263518234),
 (34, 19439.50225749169),
 (35, 18640.904748234978),
 (36, 17311.666520981536),
 (37, 16706.699658247868),
 (38, 1

In [307]:
index =[]
for i in eig_vals_sorted:
    index.append(i[0])

index

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 31,
 30,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 61,
 60,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 85,
 86,
 84,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 123,
 124,
 125,
 122,
 126,
 127,
 128,
 130,
 129,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 140,
 141,
 139,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 165,
 164,
 166,
 167,
 168,
 171,
 169,
 173,
 172,
 174,
 176,
 175,
 170,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [308]:
eig_vecs

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [309]:
eig_vecs_sorted = eig_vecs[index]

In [310]:
eig_vecs_sorted

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [312]:
eig_vecs_sorted

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [313]:
eig_vecs_T = eig_vecs_sorted.T

In [314]:
eig_vecs_T[0:2]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [315]:
df_pca= (np.dot(eig_vecs_T[0:2],X.T)).T

In [316]:
df_pca 

array([[ 207.41631559, -341.4400254 ],
       [1115.84310917, -824.27415941],
       [ 542.17678974, -365.85251841],
       ...,
       [ 419.93391345,  -63.33823283],
       [1796.5390453 , -194.06036355],
       [1076.73420129, -367.60141096]])

In [ ]:
# Use Plotly to plot PCA
"""py.sign_in('Adrienzzz', 'ibZJHrnNy0BUF6cd0G0U')
data = [go.Scatter(
    x = df_pca[:,0],
    y = df_pca[:,1],
    name = 'test',
    mode = 'markers',
    showlegend = False,
    marker = dict(
        size = 8,
        color = y,
        colorscale ='Rainbow',
        showscale = False,
        line = dict(
            width = 2,
            color = 'rgb(255, 255, 255)'
        ),
        opacity = 0.8
    )
)]

layout = go.Layout(
    title= 'Principal Component Analysis (PCA)',
    hovermode= 'closest',
    xaxis= dict(
         title= 'First Principal Component',
        ticklen= 8,
        zeroline= False,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Second Principal Component',
        ticklen= 8,
        gridwidth= 2,
    ),
    showlegend= True
)


fig = dict(data=data, layout=layout)
#py.image.save_as(fig, filename='pca.png')

py.iplot(fig, filename='PCA_plot')"""

In [317]:
# Kmeans
from lib.HomeMadeKmeans import *

In [318]:
df = pd.DataFrame()
df['x'] = [x[0] for x in df_pca]
df['y'] = [x[1] for x in df_pca]

In [319]:
df.head()

x           y
0   207.416316 -341.440025
1  1115.843109 -824.274159
2   542.176790 -365.852518
3   427.189624  468.103764
4   516.707969   -4.621292

In [320]:
itr = 2000
k=10
kmeans(itr,k,df)

[[613.7172929004806, -246.92930033385656],
 [249.98086221401, -172.05075739613295],
 [1659.6997324774545, -248.59859944779024],
 [1238.5636528073917, 84.32262943498206],
 [1311.1379769616387, -448.8854163523893],
 [506.5077877853759, 235.54827719525503],
 [891.1231723447427, -576.2934107348821],
 [834.5462440954424, 462.7278747989769],
 [1014.5705489969861, -202.95536382896194],
 [809.9183215952157, 68.440678932745]]

In [321]:
df.head()

x           y                                point_data  \
0   207.416316 -341.440025   (207.4163155916512, -341.4400254046549)   
1  1115.843109 -824.274159  (1115.8431091742086, -824.2741594100846)   
2   542.176790 -365.852518  (542.1767897440589, -365.85251840542134)   
3   427.189624  468.103764   (427.18962419509194, 468.1037643094091)   
4   516.707969   -4.621292    (516.707969188938, -4.621292107844852)   

                                            distance  cluster  
0  [417.1483684680044, 174.6552740275249, 1455.24...        1  
1  [765.1518945087356, 1084.0261974904558, 791.94...        6  
2  [138.78319562674346, 350.62456079893616, 1123....        0  
3  [738.9620116932992, 664.2294460372252, 1425.74...        5  
4  [261.00570824682706, 314.9221736269721, 1168.7...        5

In [322]:
py.sign_in('Adrienzzz', 'ibZJHrnNy0BUF6cd0G0U')
data = [
    go.Scatter(
        x= df_pca[:, 0], 
        y= df_pca[:, 1], 
        name='test',
        mode="markers",
        showlegend=False,
        marker=dict(
            size=8,
            color = df['cluster'] ,
            colorscale = 'Rainbow',
            showscale=False, 
            line = dict(
                width = 2,
                color = 'rgb(255, 255, 255)'
            )))]

layout = go.Layout(
    title= 'KMeans Clustering',
    hovermode= 'closest',
    xaxis= dict(
         title= 'First Principal Component',
        ticklen= 8,
        zeroline= False,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Second Principal Component',
        ticklen= 8,
        gridwidth= 2,
    ),
    showlegend= True
)

fig = dict(data = data, layout = layout)
py.iplot(fig, filename="kmeans_plot")

C:\Users\jiahu\Anaconda3\envs\keras\lib\site-packages\plotly\plotly\plotly.py:224: UserWarning:

Woah there! Look at all those points! Due to browser limitations, the Plotly SVG drawing functions have a hard time graphing more than 500k data points for line charts, or 40k points for other types of charts. Here are some suggestions:
(1) Use the `plotly.graph_objs.Scattergl` trace object to generate a WebGl graph.
(2) Trying using the image API to return an image instead of a graph URL
(3) Use matplotlib
(4) See if you can create your visualization with fewer data points

If the visualization you're using aggregates points (e.g., box plot, histogram, etc.) you can disregard this warning.



The draw time for this plot will be slow for all clients.


C:\Users\jiahu\Anaconda3\envs\keras\lib\site-packages\plotly\api\v1\clientresp.py:40: UserWarning:

Estimated Draw Time Too Long

