In [2]:
import numpy as np
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

In [3]:
df = pd.DataFrame()
df['V1'] = [1,2,3]
df['V2'] = [1,4,6]
df['v3'] = [1,6,7]
df['V4'] =[1,5,7]
df['V5'] = [9,5,6]

In [4]:
df

V1  V2  v3  V4  V5
0   1   1   1   1   9
1   2   4   6   5   5
2   3   6   7   7   6

In [89]:
a = list(df.mean())

In [90]:
for i in range(df.shape[1]) : 
    df.iloc[:,i] = df.iloc[:,i]-a[i]

In [91]:
df

V1        V2        v3        V4        V5
0 -1.0 -2.666667 -3.666667 -3.333333  2.333333
1  0.0  0.333333  1.333333  0.666667 -1.666667
2  1.0  2.333333  2.333333  2.666667 -0.666667

In [92]:
mean_vec = np.mean(df, axis=0)
cov_mat = (df - mean_vec).T.dot((df - mean_vec)) / (df.shape[0]-1)

In [93]:
cov_mat

V1        V2         v3        V4        V5
V1  1.0  2.500000   3.000000  3.000000 -1.500000
V2  2.5  6.333333   7.833333  7.666667 -4.166667
v3  3.0  7.833333  10.333333  9.666667 -6.166667
V4  3.0  7.666667   9.666667  9.333333 -5.333333
V5 -1.5 -4.166667  -6.166667 -5.333333  4.333333

In [94]:
cov_mat = np.cov(df.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.17444798  0.95098155 -0.25534682 -0.5928474   0.25656126]
 [ 0.45167755 -0.19019631 -0.39976588 -0.45596288  0.21682915]
 [ 0.58557433 -0.05684028  0.18836422  0.41072858  0.56270711]
 [ 0.55445913 -0.17926549 -0.28883812  0.35693929 -0.72769091]
 [-0.33945996 -0.15521768 -0.80998562  0.380166    0.20245515]]

Eigenvalues 
[ 2.99970927e+01 -6.08434327e-16  1.33624060e+00 -2.29381303e-16
  3.59707332e-16]


In [95]:
#eig_vals.sort()

In [96]:
#eig_vals

In [129]:
c = list(eig_vals)

In [130]:
eig_vals_indexed = []
for i in range(len(eig_vals)):
    eig_vals_indexed.append((i,abs(eig_vals[i])))

In [131]:
eig_vals_indexed

[(0, 29.997092728410653),
 (1, 6.08434327454825e-16),
 (2, 1.3362406049226851),
 (3, 2.2938130323569834e-16),
 (4, 3.5970733171770544e-16)]

In [132]:
eig_vecs.shape

(5, 5)

In [133]:
def getValue(l):
    return l[1]

eig_vals_sorted = sorted(eig_vals_indexed, key=getValue,reverse= True)

In [134]:
eig_vals_sorted[0]

(0, 29.997092728410653)

In [136]:
index =[]
for i in eig_vals_sorted:
    index.append(i[0])

index

[0, 2, 1, 4, 3]

In [138]:
eig_vecs

array([[ 0.17444798,  0.95098155, -0.25534682, -0.5928474 ,  0.25656126],
       [ 0.45167755, -0.19019631, -0.39976588, -0.45596288,  0.21682915],
       [ 0.58557433, -0.05684028,  0.18836422,  0.41072858,  0.56270711],
       [ 0.55445913, -0.17926549, -0.28883812,  0.35693929, -0.72769091],
       [-0.33945996, -0.15521768, -0.80998562,  0.380166  ,  0.20245515]])

In [137]:
eig_vecs[index]

array([[ 0.17444798,  0.95098155, -0.25534682, -0.5928474 ,  0.25656126],
       [ 0.58557433, -0.05684028,  0.18836422,  0.41072858,  0.56270711],
       [ 0.45167755, -0.19019631, -0.39976588, -0.45596288,  0.21682915],
       [-0.33945996, -0.15521768, -0.80998562,  0.380166  ,  0.20245515],
       [ 0.55445913, -0.17926549, -0.28883812,  0.35693929, -0.72769091]])

In [42]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original', data_home='datasets/')

# Convert sklearn 'datasets bunch' object to Pandas DataFrames
y = pd.Series(mnist.target).astype('int').astype('category')
X = pd.DataFrame(mnist.data)

In [46]:
def pca(df):
    mean_vec = np.mean(df, axis=0)
    cov_mat = (df - mean_vec).T.dot((df - mean_vec)) / (df.shape[0])
    cov_mat = np.cov(df.T)

    eig_vals, eig_vecs = np.linalg.eig(cov_mat)

    print('Eigenvectors \n%s' %eig_vecs)
    print('\nEigenvalues \n%s' %eig_vals)

In [47]:
pca(X)

Eigenvectors 
[[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]

Eigenvalues 
[ 3.34294061e+05+0.00000000e+00j  2.45433427e+05+0.00000000e+00j
  2.10930355e+05+0.00000000e+00j  1.85337356e+05+0.00000000e+00j
  1.67691572e+05+0.00000000e+00j  1.47670297e+05+0.00000000e+00j
  1.12445139e+05+0.00000000e+00j  9.91153833e+04+0.00000000e+00j
  9.46125388e+04+0.00000000e+00j  8.03359569e+04+0.00000000e+00j
  7.22599113e+04+0.00000000e+00j  6.98885540e+04+0.00000000e+00j
  5.85527059e+04+0.00000000e+00j  5.81052758e+04+0.00000000e+00j
  5.43103821e+04+0.00000000e+00j  5.09819786e+04+0.00000000e+00j
  4.52543057e+04+0.00000000e+00j  4.38704888e+04+0.00000000e+00j
  4.07237248e+04+0.00000000e+00j  3.95459992e+04+0.00000000e+00j
  3.65654146e+04+0.000